spring:
  application:
    name: eurka-provider
  boot:
    admin:
      client:
        url: http://localhost:8899
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      enabled: true

server:
  port: 8763
eureka:
  client:
    serviceUrl:
      defaultZone: http://node1:8761/eureka/,http://node2:8762/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
    appname : eurka-provider
    metadata-map:
      ckx: "大家好"