server:
  port: 8766

spring:
  application:
    name: eureka-client2
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://node1:8761/eureka/,http://node2:8762/eureka/
#  instance:
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
#    prefer-ip-address: true
#    appname : eurka-clien
eureka:
  client:
    #是否将自己注册到Eureka Server,默认为true
    registerWithEureka: false
    #是否从eureka server获取注册信息
    fetchRegistry: true
provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule