server:
  port: 8862
eureka:
  client:
    serviceUrl:
      defaultZone: http://node1:8761/eureka/,http://node2:8762/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
    appname : eurka-provider
    metadata-map:
      ckx: "大家好"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true