server:
  port: 8899



spring:
  application:
    name: server-admin
  # 邮件设置
  mail:
    host: smtp.qq.com
    username: 41195198@qq.com
    password: kbzstuguobdcbhci
    properties:
      mail:
        smpt:
          auth: true
          starttls:
            enable: true
            required: true
#收件邮箱
spring.boot.admin.notify.mail.to: 41195198@qq.com
# 发件邮箱
spring.boot.admin.notify.mail.from: 41195198@qq.com
