server:
  port: 8762
spring:
  application:
    name: eurka-server
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    hostname: node2
    appname : eurka-server
  client:
    #是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    registerWithEureka: true
    #是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    fetchRegistry: true
    #设置服务注册中心的URL，用于client和server端交流
    serviceUrl:
      defaultZone: http://node1:8761/eureka/
management:
  endpoint:
    shutdown:
      enabled: true
